### ISSUE TITLE
Poor results or wrong useage of GLEAN in face images.

### ISSUE THREAD

**Issue by ewrfcas** [ckkelvinchan/GLEAN#3]
Hi, I have tried GLEAN in mmediting for 64->1024 face SR. But the generated results are very poor.
My command is python restoration_demo.py configs/restorers/glean/glean_ffhq_16x.py workdirs/glean_ffhq_16x_20210527-61a3afad.pth tests/data/1009.png preds/1009.png --device 2

My input is 64x64 face image
![image](https://user-images.githubusercontent.com/12042259/121626092-5a674a80-caa7-11eb-826a-e1ff647d2bcf.png)
and the output is
![image](https://user-images.githubusercontent.com/12042259/121626123-6bb05700-caa7-11eb-80fd-0325f3374ebe.png)

**Comment by ewrfcas** [comment]
Here is the log
![image](https://user-images.githubusercontent.com/12042259/121626462-1163c600-caa8-11eb-9208-e81611a168d9.png)

**Comment by ckkelvinchan** [comment]
Hello, did you use bicubic downsampling kernel?

In addition, it seems that `restoration_inference` did not normalize the images from [-1, 1] back to [0, 1]. As a workaround, you can normalize the output in your backbone by using `output = (output + 1) / 2.0` and see how the results look. I will see how to modify `restoration_inference` later.

**Comment by yzxing87** [comment]
Same issue here. In my case, the max value of `output` exceeds 1 and the min value is greater than 0.

**Comment by ckkelvinchan** [comment]
> Hello, did you use bicubic downsampling kernel?
> 
> In addition, it seems that `restoration_inference` did not normalize the images from [-1, 1] back to [0, 1]. As a workaround, you can normalize the output in your backbone by using `output = (output + 1) / 2.0` and see how the results look. I will see how to modify `restoration_inference` later.

I am sorry that it seems that this is not the problem. The code should have normalized it back to [0, 1]. 

I just tried two images in CelebA-HQ and they work fine. Could you please try the images in CelebA-HQ? Please note that MATLAB `imresize` should be used for downsampling.

**Comment by ckkelvinchan** [comment]
How about trying the images [here](https://github.com/ckkelvinchan/GLEAN/files/6636748/celeba-hq.zip)? These two images work fine on my side.

**Comment by yzxing87** [comment]
> How about trying the images [here](https://github.com/ckkelvinchan/GLEAN/files/6636748/celeba-hq.zip)? These two images work fine on my side.

Hi, I have tried your images with command 

```
python demo/restoration_demo.py configs/restorers/glean/glean_ffhq_16x.py \
    pretrain/glean_ffhq_16x_20210527-61a3afad.pth \
    00001.png \
    results/00001.png \
    --device 1
```
But the output is still poor. 

Is it because of my wrong usage? Thank you

**Comment by ckkelvinchan** [comment]
I used this command: 
```
python demo/restoration_demo.py configs/restorers/glean/glean_ffhq_16x.py https://download.openmmlab.com/mmediting/restorers/glean/glean_ffhq_16x_20210527-61a3afad.pth ./00001.png outputs/00001.png
```

Did you modify the codes? 

Here are my results: [results.zip](https://github.com/ckkelvinchan/GLEAN/files/6637287/results.zip)

**Comment by ewrfcas** [comment]
Still fails with bicubic resizing and data rescaling to [0,1].
Here is the code in restoration_inference.py
![image](https://user-images.githubusercontent.com/12042259/121666044-6ff66780-cadb-11eb-8404-3147542f0603.png)
Failed results.

**Comment by ckkelvinchan** [comment]
> Still fails with bicubic resizing and data rescaling to [0,1].
> Here is the code in restoration_inference.py
> ![image](https://user-images.githubusercontent.com/12042259/121666044-6ff66780-cadb-11eb-8404-3147542f0603.png)
> Failed results.

How about removing `data['lq'] = (data(['lq'] + 1) / 2)`. When adding this line, the input to the network would be [0, 1], which is incorrect.

I used the latest version of MMEditing codes without any modifications.

**Comment by ewrfcas** [comment]
The output should be converted back to [-1,1]?

**Comment by ckkelvinchan** [comment]
> The output should be converted back to [-1,1]?

The code will handle the conversion itself. There is no need to modify the code. The original code will do.

**Comment by ewrfcas** [comment]
> > Still fails with bicubic resizing and data rescaling to [0,1].
> > Here is the code in restoration_inference.py
> > ![image](https://user-images.githubusercontent.com/12042259/121666044-6ff66780-cadb-11eb-8404-3147542f0603.png)
> > Failed results.
> 
> How about removing `data['lq'] = (data(['lq'] + 1) / 2)`. When adding this line, the input to the network would be [0, 1], which is incorrect.
> 
> I used the latest version of MMEditing codes without any modifications.

Sorry, I am confused for the input range. Which is the correct value range, [0,1] or [-1,1]?

**Comment by ckkelvinchan** [comment]
> > > Still fails with bicubic resizing and data rescaling to [0,1].
> > > Here is the code in restoration_inference.py
> > > ![image](https://user-images.githubusercontent.com/12042259/121666044-6ff66780-cadb-11eb-8404-3147542f0603.png)
> > > Failed results.
> > 
> > 
> > How about removing `data['lq'] = (data(['lq'] + 1) / 2)`. When adding this line, the input to the network would be [0, 1], which is incorrect.
> > I used the latest version of MMEditing codes without any modifications.
> 
> Sorry, I am confused for the input range. Which is the correct value range, [0,1] or [-1,1]?

The inputs and outputs of GLEAN will be [-1, 1]. But you do not need to modify the code, as I have implemented the conversion.

**Comment by ewrfcas** [comment]
> > > > Still fails with bicubic resizing and data rescaling to [0,1].
> > > > Here is the code in restoration_inference.py
> > > > ![image](https://user-images.githubusercontent.com/12042259/121666044-6ff66780-cadb-11eb-8404-3147542f0603.png)
> > > > Failed results.
> > > 
> > > 
> > > How about removing `data['lq'] = (data(['lq'] + 1) / 2)`. When adding this line, the input to the network would be [0, 1], which is incorrect.
> > > I used the latest version of MMEditing codes without any modifications.
> > 
> > 
> > Sorry, I am confused for the input range. Which is the correct value range, [0,1] or [-1,1]?
> 
> The inputs and outputs of GLEAN will be [-1, 1]. But you do not need to modify the code, as I have implemented the conversion.

Thanks. I use the original codes to test the image given above, but the result is still failed.
![image](https://user-images.githubusercontent.com/12042259/121668265-b6e55c80-cadd-11eb-9381-fc2845fd76ad.png)

**Comment by ckkelvinchan** [comment]
I am able to reproduce your error just now. Please remove `--device 1`. I will investigate why and please remove it for the moment.

**Comment by yzxing87** [comment]
Thanks, removing `device` works! It seems that the data and the model are placed on different devices. If I set the `CUDA_VISIBLE_DEVICES` in the very beginning, the demo can also work fine when `--device` is set to other GPUs.

**Comment by ewrfcas** [comment]
> I am able to reproduce your error just now. Please remove `--device 1`. I will investigate why and please remove it for the moment.

Nice，it works. Maybe the model failed to load weights properly with --device?

**Comment by ckkelvinchan** [comment]
It may be, thank you for letting me know :) I will look into the problem~

I will keep this issue open for the moment in case others encounter this problem. Thanks again.

**Comment by BrotherQi** [comment]
The experimental results are correct on the data you provided， I got an error using the resize method of cv2。

cv2.resize(img, (64, 64), interpolation=cv2.INTER_CUBIC)


So I want to ask whether the glean method does not generalize to wild data
